apiVersion: v1
kind: ConfigMap
metadata:
  name: loyalty-mysql-config
  labels:
    app: loyalty-db
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    max_connections=200
    innodb_buffer_pool_size=512M
    innodb_log_file_size=128M
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci

