apiVersion: v1
kind: Service
metadata:
  name: loyalty-frontend
  labels:
    app: loyalty-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: loyalty-frontend

